---
- name: Install Wazuh Agent
  hosts: linux
  become: yes
  gather_facts: yes

  vars:
    wazuh_manager: "wazuh01.lab.subnetphantom.com"
    wazuh_group: "default"
    wazuh_version: "4.14.6-1"

  tasks:

    - name: Download Wazuh agent package
      ansible.builtin.get_url:
        url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_{{ wazuh_version }}_amd64.deb"
        dest: "/tmp/wazuh-agent_{{ wazuh_version }}_amd64.deb"
        mode: '0644'

    - name: Install Wazuh agent
      ansible.builtin.apt:
        deb: "/tmp/wazuh-agent_{{ wazuh_version }}_amd64.deb"
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
        WAZUH_AGENT_GROUP: "{{ wazuh_group }}"

    - name: Enable Wazuh agent
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start Wazuh agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started